### ISSUE TITLE
NodeJS install issue

### ISSUE THREAD

**Issue by Protoneer** [ARMinARM/arminarm#2]
Hi. 

I just assembled my board and I am running the latest Jesse OS for RPI.

I select the Install NodeJS option and I get an error saying that it can't be installed. I have seen this happen before and my work around is usually to follow the installation details Adafruit provides.
https://learn.adafruit.com/node-embedded-development/installing-node-dot-js

Nice setup by the way!!!

**Comment by ARMinARM** [comment]
I've seen it not work on Wheezy because of 'GLIBCXX\* not found', but I was able to install it on Jessie Lite. I'll do some digging and leave this issue open.

Thanks for the link!

**Comment by ARMinARM** [comment]
Thanks for the constructive conversation we have about this by email.

There are no strict dependencies on node.js for anything ARMinARM related. For now, the menu item is removed.
