### ISSUE TITLE
Flasing Espruino seems to do nothing. (Espruino not running)

### ISSUE THREAD

**Issue by Protoneer** [ARMinARM/arminarm#3]
I am trying option 10 and I am getting the following back.(below)

It goes very fast and the serial interface does not respond. (I tried the Lua example and that takes a while to write and seems to work over serial)

Any idea what I am doing wrong?

```
Enter your choice:
10
UPLOADING ESPRUINO.BIN
Found espruino_ARMinARM.bin
flashing espruino_1v83_ARMinARM.bin using stm32flash
stm32flash 0.4

http://stm32flash.googlecode.com/

Using Parser : Intel HEX
Interface serial_posix: 115200 8E1
Version      : 0x22
Option 1     : 0x00
Option 2     : 0x00
Device ID    : 0x0414 (High-density)
- RAM        : 64KiB  (512b reserved by bootloader)
- Flash      : 512KiB (sector size: 2x2048)
- Option RAM : 16b
- System RAM : 2KiB
Write to memory
Erasing memory
Done.

Resetting device... done.

espruino communicates on 9600 baud on /dev/ttyAMA0
```

**Comment by ARMinARM** [comment]
We did some troubleshooting by email.

Sometimes (especially after boot/reboot) the arminarm board needs an explicit reset. Either by pressing the reset button, or `arminarm -r` command. After a second try it usually works.

Uploading espruino.bin should take around 40 seconds, and there should be a progress counter showing the 'percentage done'.

Closing this issue for now. You're welcome to re-open it or create another issue.
